title: Regal Ravioli
baseurl: "/regal-ravioli"
url: "http://davidpowellme.github.io" # the base hostname & protocol for your site
twitter_username: davidpowellme
github_username:  davidpowellme

# Build settings
markdown: kramdown
